/* SPDX-License-Identifier: MIT */
/*
 * Copyright (c) 2019, Blue Origin.
 *
 * Authors: Andrey Smirnov <andrew.smirnov@gmail.com>
 *          Benjamin Kamath <kamath.ben@gmail.com>
 */
#ifndef HERCULES_ESM_H
#define HERCULES_ESM_H

enum {
    HERCULES_ESM_IRQ_HIGH     = 0,
    HERCULES_ESM_IRQ_LOW      = 1,
    HERCULES_ESM_NUM_IRQS = 2,
    HERCULES_ESM_NUM_GROUP1 = 96,
    HERCULES_ESM_NUM_GROUP2 = 32,

    HERCULES_NUM_ESM_CHANNELS = 160,
};

#define HERCULES_ESM_GROUP1(n)  (n)
#define HERCULES_ESM_GROUP2(n)  (HERCULES_ESM_NUM_GROUP1 + (n))
#define HERCULES_ESM_GROUP3(n)  (HERCULES_ESM_NUM_GROUP2 + \
                                 HERCULES_ESM_GROUP2(n))

enum HerculesESMChannels {
    HERCULES_MIBADC2_PARITY_ERROR = HERCULES_ESM_GROUP1(1),
    HERCULES_EPC_CORRECTABLE_ERROR = HERCULES_ESM_GROUP1(4),
    HERCULES_PLL1_SLIP_ERROR = HERCULES_ESM_GROUP1(10),
    HERCULES_MIBADC1_PARITY_ERROR = HERCULES_ESM_GROUP1(19),

    HERCULES_CCMR5F_SELF_TEST_ERROR = HERCULES_ESM_GROUP1(31),
    HERCULES_PMM_COMPARE_ERROR   = HERCULES_ESM_GROUP1(38),
    HERCULES_PMM_SELF_TEST_ERROR = HERCULES_ESM_GROUP1(39),
    HERCULES_EFUSE_SINGLE_BIT_ERROR = HERCULES_ESM_GROUP1(40),
    HERCULES_EFUSE_SELF_TEST_ERROR = HERCULES_ESM_GROUP1(41),
    HERCULES_PLL2_SLIP_ERROR = HERCULES_ESM_GROUP1(42),

    HERCULES_MIBSPI1_SINGLE_BIT_ERROR    = HERCULES_ESM_GROUP1(77),
    HERCULES_MIBSPI2_SINGLE_BIT_ERROR    = HERCULES_ESM_GROUP1(78),
    HERCULES_MIBSPI3_SINGLE_BIT_ERROR    = HERCULES_ESM_GROUP1(79),
    HERCULES_MIBSPI4_SINGLE_BIT_ERROR    = HERCULES_ESM_GROUP1(80),
    HERCULES_MIBSPI5_SINGLE_BIT_ERROR    = HERCULES_ESM_GROUP1(81),

    HERCULES_MIBSPI1_UNCORRECTABLE_ERROR = HERCULES_ESM_GROUP1(17),
    HERCULES_MIBSPI2_UNCORRECTABLE_ERROR = HERCULES_ESM_GROUP1(49),
    HERCULES_MIBSPI3_UNCORRECTABLE_ERROR = HERCULES_ESM_GROUP1(18),
    HERCULES_MIBSPI4_UNCORRECTABLE_ERROR = HERCULES_ESM_GROUP1(50),
    HERCULES_MIBSPI5_UNCORRECTABLE_ERROR = HERCULES_ESM_GROUP1(24),

    HERCULES_CCMR5F_CPU_COMPARE_ERROR    = HERCULES_ESM_GROUP2(2),
    HERCULES_CR5F_FATAL_BUS_ERROR        = HERCULES_ESM_GROUP2(3),
    HERCULES_L2RAMW_TYPE_B_UNCORRECTABLE_ERROR = HERCULES_ESM_GROUP2(7),
    HERCULES_CCMR5F_VIM_COMPARE_ERROR    = HERCULES_ESM_GROUP2(25),
    HERCULES_CPU1_AXIM_BUS_MONITOR_ERROR = HERCULES_ESM_GROUP2(26),

    HERCULES_EFUSE_AUTOLOAD_ERROR        = HERCULES_ESM_GROUP3(1),

    HERCULES_L2FMC_UNCORRECTABLE_ERROR   = HERCULES_ESM_GROUP3(13),
};

typedef struct HerculesESMState {
    SysBusDevice parent_obj;

    MemoryRegion iomem;

    uint32_t esmsr[5];
    uint32_t esmil[5];
    uint32_t esmie[5];
    uint32_t esmiep[5];

    unsigned int irq_state;
    qemu_irq irq[HERCULES_ESM_NUM_IRQS];
} HerculesESMState;

#define TYPE_HERCULES_ESM "ti-hercules-esm"
#define HERCULES_ESM(obj) OBJECT_CHECK(HerculesESMState, (obj), \
                                       TYPE_HERCULES_ESM)
#endif
